### ISSUE TITLE
TEST ALL THE THINGS!!1!

### ISSUE THREAD

**Issue by astorije** [erming/shout#492] opened 2015-09-28 20:19 UTC
As of today, we have only one test: the link plugin. Sadly, prefetching is now disabled by default, which makes our only test very sad :-)

Testing is becoming important as we are now merging all the PRs that our lovely contributors.

If you are willing to help on Shout, writing tests would be very much appreciated! Thanks so much in advance.

**Comment by floogulinc** [comment] 2015-09-29 14:22
I noticed on the dev branch, testing was changed to using tape instead of mocha, and there are a lot of tests there. I bet there are quite a few things in general we can grab from the dev branch.

**Comment by JocelynDelalande** [comment] 2015-09-29 19:32
@astorije yep, for sure we should be able to test… but that's a duplicate of #351 (I let you closing one of the 2 tickets...)

**Comment by astorije** [comment] 2015-10-02 10:57
@floogulinc, I'm generally not into changing the lib used just like that (mocha in that case), but I'm all in favor for tests. @erming, would you mind PRing your tests from `dev` to `master`? Also, PRing `dev` early rather than late would be great as other contributors could be prepared for that, but that's a different topic :-)

@JocelynDelalande, yes, closing this and moving the labels over there. Sorry I got too excited and forgot to use search field and to unlock caps :D

**Closed** 2015-10-02 10:57 UTC
Labels: duplicate, help wanted, priority
