### ISSUE TITLE
New message indicator

### ISSUE THREAD

**Issue by eliemichel** [erming/shout#338] opened 2015-01-13 08:30 UTC
Drawing a line between new messages and old message as in ncurse weechat interface or in [GlowingBear](http://www.glowing-bear.org/) would be really nice!

**Comment by deejayy** [comment] 2015-01-16 20:35
+1 for this, i already noted to myself.

**Comment by sc0tt** [comment] 2015-01-17 15:57
+1

**Comment by josegonzalez** [comment] 2015-02-28 06:28
Duplicate of #206

**Closed by josegonzalez** 2015-02-28 06:28 UTC
