### ISSUE TITLE
Charset and User Real IP

### ISSUE THREAD

**Issue by TuSuNaMi** [erming/shout#447] opened 2015-07-22 13:51 UTC
Hello;

I need some help with charset and real ip. I wanna change client view charset to iso-8859-9 and I need my clients connect to server require client real ip address. How can i solve this ?

http://m.sohbetodam.org/

My url is here please help me
Thanks

**Comment by TuSuNaMi** [comment] 2015-07-23 07:15
Real IP problem solved but charset problem continue

**Comment by gburgwardt** [comment] 2015-07-23 15:07
TuSuNaMi - 

I'm trying to get the users to show their real IP when you /whois them - did you figure out how to do that? I would love to hear how. I'll see what I can do about changing the charset in return :)

**Comment by TuSuNaMi** [comment] 2015-07-23 16:19
Hello;

I use @AmShaegar13 's webirc patch. It use IRC Server's CGI:IRC protocol.

https://raw.githubusercontent.com/AmShaegar13/shout/6059d6b29367534098206208f72650c13160fd80/defaults/config.js

https://raw.githubusercontent.com/AmShaegar13/shout/6059d6b29367534098206208f72650c13160fd80/src/client.js

and modified reverse dns patch

https://raw.githubusercontent.com/AmShaegar13/shout/9849d301c4fb1851d79fc0c0da130be62ef2ce7e/src/server.js

First file you need set web server IP and password to IRCD 's CGI:IRC config. 

Example my Web Server IP 1.1.1.1

My IRCD Config (inspircd 2.x)

<cgihost type="webirc" password="password" mask="1.1.1.1">  #set to web server ip

**Comment by TuSuNaMi** [comment] 2015-07-24 11:19
Character set problem continue.

I need urgently help for this 

Thanks
![problem](https://cloud.githubusercontent.com/assets/2782969/8873414/0bea5276-320f-11e5-81d9-78db3cc0506d.png)

**Comment by JocelynDelalande** [comment] 2015-09-26 21:14
@TuSuNaMi can you be a bit more clear about what you want to do with charset (or, if no longer relevant, could we close this issue ?)

**Comment by TuSuNaMi** [comment] 2015-09-26 21:30
for Inspircd I must set charset to iso-8859-9 for turkish nicknames and channel names. 
but shout only support utf8 language iso-8859-9 and utf-8 cannot agree on display vision

**Comment by JocelynDelalande** [comment] 2015-09-27 22:08
> for Inspircd I must set charset to iso-8859-9 for turkish nicknames and channel names.

@TuSuNaMi are you saying that there are characters in turkish language that are not included into utf-8 charset ?

**Comment by AmShaegar13** [comment] 2015-09-27 22:22
I think the problem is that the network uses another charset than shout.

**Comment by JocelynDelalande** [comment] 2015-09-28 18:32
> I think the problem is that the network uses another charset than shout.

Yes, I suppose so, but I want to be sure of what we are speaking about.

**Comment by TuSuNaMi** [comment] 2015-09-28 18:54
Hello sorry for delay

@AmShaegar13 yes my network use different charset. Inspircd not support well Utf-8 language

and

@JocelynDelalande my network use iso-8859-9 charset for turkish channel and nicknames.

**Comment by JocelynDelalande** [comment] 2015-09-28 20:05
@TuSuNaMi I opened #490 with the issue worded as such (+ my opinion on it). Thanks for taking time to report, if you (or anyone) have motivation and can come with a PR, I would be happy to review it :)

> @JocelynDelalande my network use iso-8859-9 charset for turkish channel and nicknames.

That goes in same way that what I say in #490 : I think the right approach is to focus on making the switch to utf-8 (and using tools supporting it), fixing broker software rather than adding legacy code to working ones.

**Closed** 2015-09-28 20:06 UTC
Labels: question
