### ISSUE TITLE
Interface does not saves Networks/irc channel on disconnections 

### ISSUE THREAD

**Issue by dannyti** [erming/shout#530] opened 2015-11-03 02:08 UTC
Interface does not saves Networks/irc channel on disconnection. 

If I disconnect from a network, the network is not saved. I logout and then login again and I have to start from scratch.

Also , can we have the password change and commands on joining server, nickserv password at the User interface ?

Thank You.

**Comment by astorije** [comment] 2015-11-05 03:52
Hi,

Thanks for your report.
However, these have already reported in the past, so make sure to use the search feature that GitHub provides. In general, make sure to read our [CONTRIBUTING file](https://github.com/erming/shout/blob/master/CONTRIBUTING.md) which will help you navigating through our issues and pull requests :-)
Finally, in the future though, make sure to only report one bug per ticket otherwise it is really hard to track.

Regarding the networks not being saved, this is a duplicate of https://github.com/erming/shout/issues/475.

Front-end password changing has been proposed in https://github.com/erming/shout/pull/506, I need to find some time to review now.

Closing this issue with `duplicate` labels. You can subscribe to the links given above to be notified on progress.

**Closed by astorije** 2015-11-05 03:52 UTC
Labels: duplicate
