### ISSUE TITLE
Infer command from short commands

### ISSUE THREAD

**Issue by dbkaplun** [erming/shout#433] opened 2015-06-02 15:47 UTC
One way to do this: if you type in a command like `/j`, every available command should be matched against `/j`. If an exact match exists, then use that, otherwise find all commands that start with `/j`. If there is only one (like `/join`), then assume the user meant `/join`. If there are more than one, then tell the user the command cannot be inferred, and list the possibilities.

**Comment by astorije** [comment] 2015-09-26 00:58
I think this would have terrible consequences in User eXperience. In human perception, this would mean that `/join` has 3 aliases: `/j`, `/jo` and `/joi`. If someday we add `/j` for some reason, it will take over `/j` and surprise everyone.

Also, I do think there is a sort-of fix for this already. If you type `/j` then hit `Tab`, it will auto-complete to  `/join`, that you validate with `Return`. Yes, it adds one more step than your example (hitting `Tab`), but much more predictable in terms of UX.
What do you think of this solution? And what are @erming and @JocelynDelalande's take on this?

**Comment by floogulinc** [comment] 2015-09-26 07:41
This is a duplicate of #364. We did this in Shuo-IRC/Shuo#30

**Comment by astorije** [comment] 2015-09-26 09:01
Closing this as duplicate then.

**Closed** 2015-09-26 09:02 UTC
Labels: duplicate, enhancement, feature
