### ISSUE TITLE
Needing help to run shout on bootup

### ISSUE THREAD

**Issue by YugiFanGX** [erming/shout#549] opened 2015-12-03 12:06 UTC
I sucessfully installed shout and it is working. Now I noticed, that shout does not start automatically on bootup. How can I archieve this? I created a new file in /etc/cron.d/boot, where I inserted the following:
#!/bin/bash
shout start

Unfortunately, this does not work for me. Can someone help me?

**Comment by z8po** [comment] 2015-12-03 12:36
launching script with Forever (:~$ forever start index.js) and make a Service script ( in /etc/init.d/) instead of cron. and use absolute path. something like that http://www.slidequest.com/q/70ang

**Comment by YugiFanGX** [comment] 2015-12-03 12:45
Could you be a bit more precise? From which directory do I have to run the "forever start index.js" command?
And also, what do I have to write into the newly created file in /etc/init.d/ ?

Thank you for your support

**Comment by Xe** [comment] 2015-12-03 15:34
You should be creating an upstart job or systemd unit, not relying on cron. Cron will not restart the service when it dies.

**Comment by JocelynDelalande** [comment] 2015-12-03 16:45
@YugiFanGX Hi, that's quite a duplicate of #170 where you will find a couple of options. Would be good to provide an official method included with the project though.

**Closed** 2015-12-03 16:45 UTC
Labels: question

**Comment by YugiFanGX** [comment] 2015-12-04 08:14
Now I created a file in /etc/init.d/shout/ with the following content:
#!/bin/bash
shout start

It did not start on the boot either. Can you tell me what you placed in init.d?
