### ISSUE TITLE
User config not retained after disconnecting

### ISSUE THREAD

**Issue by TheSonAlsoRises** [erming/shout#376] opened 2015-03-19 09:23 UTC
I am not sure if that is a bug or SOP, but I have the following issue (using shout 0.50.0 in private mode):

1. I edit my user config with a server, multiple channels and custom commands.
2. I login with shout and connect to said server.
3. Later, I disconnect from the server and logout.
4. When I connect again, the server, channels and commands are back to the default values on the interface. They are also deleted from the user's json.

**Comment by erming** [comment] 2015-03-23 00:02
I'm sorry to say tell you that this is working as intended.

If you manually disconnect from a network, that information is deleted from the `user.json`. However, the network information is kept between Shout restarts, which was the intended use-case when I implemented this feature, mostly for painless auto-connecting after server restarts.

Maybe you could set your defaults in your `config.js`?
https://github.com/erming/shout/blob/master/defaults/config.js#L111-L183

I'll go ahead and close this issue.

**Closed by erming** 2015-03-23 00:02 UTC
