### ISSUE TITLE
 Cannot call method 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by anonprophet** [erming/shout#438] opened 2015-06-04 13:46 UTC
often get ERROR below
```
/home/shout/node_modules/shout/node_modules/slate-irc/lib/plugins/whois.js:103
          var target = params[1].toLowerCase();
                                 ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at Client.<anonymous> (/home/shout/node_modules/shout/node_modules/slate-irc/lib/plugins/whois.js:103:34)
    at Client.EventEmitter.emit (events.js:117:20)
    at Client.onmessage (/home/shout/node_modules/shout/node_modules/slate-irc/index.js:355:8)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Parser.online (/home/shout/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/index.js:88:8)
    at Stream.EventEmitter.emit (events.js:95:17)
    at pushData (/home/shout/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/node_modules/linewise/lib/linewise.js:98:10)
    at Stream.write (/home/shout/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/node_modules/linewise/lib/linewise.js:62:16)
    at Parser.write (/home/shout/node_modules/shout/node_modules/slate-irc/node_modules/slate-irc-parser/index.js:45:24)
    at write (_stream_readable.js:583:24)
root@app:/home/shout/node_modules/shout#
```

how to reproduce this error : 
```
Login and Click one of user in Right sidebar or in Chat
```

**Comment by astorije** [comment] 2015-09-26 00:43
I am afraid I cannot reproduce this.
- Is it still a problem for you?
- Did you have any problem while installing the dependencies? If so or if you don't remember, can you update Shout and check if this still happens?
- Does anyone else meet this bug?

**Comment by astorije** [comment] 2015-12-14 03:20
It's been a month and a half since my answer and more than 6 months since the author opened this issue. Therefore I'm closing this, feel free to comment and/or reopen if someone can reproduce.

**Closed** 2015-12-14 03:20 UTC
Labels: bug
